package com.limitless.haulified.Haulifier.webaccess;

public enum ServiceMethods {
    WS_LOGIN,
    WS_GET_PRODUCTS,
    WS_GET_PRODUCT_DETAIL,
    WS_ADD_TO_CART,
    WS_GET_CART_ITEM,
    WS_GET_PATIENT,
    WS_POST_PATIENT,
    WS_GET_ORDER_LIST,
    WS_DELETE_CART_ITEM,
    WS_PLACE_ORDER,
    WS_GET_FILTER,
    WS_ADD_ORDER_IN_QUEUE,
    WS_QUANTITY_UPDATE,
    WS_DASHBOARD,
    WS_CHANGEPWD,
    WS_ADD_REPAIR,
    WS_REPAIR_LIST,
    WS_APPROVE_REPAIR_LIST,
    WS_FORGET,
    WS_UPLOAD_PROFILE_IMAGE

}
